[project]
name = "user-identity-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.3",
    "asyncpg>=0.31.0",
    "cryptography>=46.0.4",
    "fastapi[standard]>=0.128.0",
    "psycopg2>=2.9.11",
    "python-jose[cryptography]>=3.5.0",
    "rich>=14.3.1",
    "sqlalchemy>=2.0.46",
]

[dependency-groups]
dev = [
    "black>=26.1.0",
    "httpx>=0.28.1",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
    "pytest-instafail>=0.5.0",
    "pytest-sugar>=1.1.1",
    "pytest-xdist>=3.8.0",
    "ruff>=0.14.14",
]

[tool.pytest.ini_options]
python_files = ["test_*.py"]
python_functions = ["test_*"]
asyncio_mode = "auto"
addopts = "-s -v -ra"
pythonpath = ["src"]
markers = [
  "unit: fast tests without external deps",
  "integration: tests that hit db/app"
]
